module.exports = {
  env: {
    NEXT_PUBLIC_API_ENDPOINT: "http://localhost:3001",
    FIREBASE_ADMIN_TYPE: "",
    FIREBASE_ADMIN_PROJECT_ID: "",
    FIREBASE_ADMIN_PRIVATE_KEY_ID: "",
    FIREBASE_ADMIN_PRIVATE_KEY: "",
    FIREBASE_ADMIN_CLIENT_EMAIL: "",
    FIREBASE_ADMIN_CLIENT_ID: "",
    FIREBASE_ADMIN_AUTH_URI: "",
    FIREBASE_ADMIN_TOKEN_URI: "",
    FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL: "",
    FIREBASE_ADMIN_CLIENT_X509_CERT_URL: "",
  },
};
